In [2]:
 import numpy as np

In [3]:
a = np.array([2,3,4])

In [4]:
a

array([2, 3, 4])

In [5]:
a.dtype

dtype('int32')

In [6]:
a.dtype.name

'int32'

In [7]:
a.itemsize

4

In [8]:
a.size

3

In [9]:
type(a)

numpy.ndarray

In [10]:
b = np.array([1.2, 3.5, 5.1])

In [11]:
b

array([ 1.2,  3.5,  5.1])

In [12]:
b.dtype

dtype('float64')

In [13]:
b.dtype.name

'float64'

In [14]:
b.itemsize

8

In [15]:
b.size

3

In [16]:
type(b)

numpy.ndarray

In [17]:
b = np.array([(1.5,2,3), (4,5,6)])

In [18]:
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [20]:
 c = np.array( [ [1,2], [3,4] ], dtype=complex )#karmaşık sayı haline getirir

In [21]:
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [22]:
np.zeros( (3,4) ) #3*4

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [23]:
np.ones( (2,3,4), dtype=np.int16 ) # 2 tane 3*4 matris yaz

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [24]:
np.ones( (3,3,4), dtype=np.int16 )#3 tane 3*4 matris yaz

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [25]:
np.arange( 10, 30, 5 ) # 10 dan 30 a kadar 5 er 5 er

array([10, 15, 20, 25])

In [26]:
np.arange( 0, 2, 0.3 )  #0 dan 2 ye kadar 0.3 er 0.3 er

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [27]:
np.linspace( 0, 2, 9 ) 

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [28]:
np.linspace( 10, 20, 5 ) #[(son terim -ilk terim)/artış miktarı ]+1 //[(20-10)/artış miktarı]+1=5 ise artış mikatrı 2.5 olur.

array([ 10. ,  12.5,  15. ,  17.5,  20. ])

In [29]:
np.linspace( 0, 5, 5) 

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ])

In [30]:
np.linspace( 10, 20, 5 ) 

array([ 10. ,  12.5,  15. ,  17.5,  20. ])

In [31]:
c = np.arange(24).reshape(2,3,4) #0 dan 24 e kadar olan sayıları 2 tane 3*4 matris yap 

In [32]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [34]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [35]:
a = np.array( [20,30,40,50] )

In [36]:
a<35

array([ True,  True, False, False], dtype=bool)

In [37]:
a<30

array([ True, False, False, False], dtype=bool)

In [38]:
a<=30

array([ True,  True, False, False], dtype=bool)

In [39]:
b = np.arange(12).reshape(3,4)

In [40]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
b.sum(axis=0)  # sum of each column

array([12, 15, 18, 21])

In [42]:
b.sum(axis=1) # sum of each row

array([ 6, 22, 38])

In [44]:
b.min(axis=0) #min of each column

array([0, 1, 2, 3])

In [45]:
b.min(axis=1) #min of each row

array([0, 4, 8])

In [46]:
b.cumsum(axis=0) #cumulative sum along each column

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

In [47]:
b.cumsum(axis=1) #cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)