In [4]:
import numpy as np
a=np.array([1,2,3],float)
b=np.array([-1,-3,-76],int)
print (a,b)


[ 1.  2.  3.] [ -1  -3 -76]


In [11]:
a.shape,b.shape #the shape of an array is a tuple of integers giving the size of the array along each dimension.

((3,), (3,))

In [13]:
a.itemsize,b.itemsize #itemsize:float=8 and int=4 bytes (Bytes per element)

(8, 4)

In [14]:
a.dtype,b.dtype

(dtype('float64'), dtype('int32'))

In [16]:
type(a) #checking array a type

numpy.ndarray

In [17]:
type(b) #checking array b type

numpy.ndarray

In [18]:
a.dtype.name #array a type name

'float64'

In [19]:
b.dtype.name #array b type name

'int32'

In [20]:
type(a[0]) #array a[0] type name

numpy.float64

In [22]:
type(b[2]) #array b[2] type name

numpy.int32

In [23]:
type(a[1]) is type(a[2]) #numpy.float64==numpy.float64

True

In [24]:
type(a[1]) is type(b[2]) #numpy.float64!=numpy.int32

False

In [25]:
a.size #array a size

3

In [26]:
b.size #array b size

3

In [33]:
b = np.arange(12).reshape(3,4) # 3 * 4 type matrix consisting of numbers 0 to 12
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
b = np.arange(12).itemsize 
b

4

In [43]:
b = np.arange(12.0).reshape(3,4)
b

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [46]:
b = np.arange(12).nbytes # Multiplies 12 elements by the number of bytes per element(4).
b

48

In [47]:
b = np.arange(12).ndim #number of dimensions
b

1

In [50]:
e = a.copy() #create copy of the array a 
e

array([ 1.,  2.,  3.])

In [53]:
e.tolist() #convert a numpy array to a python list.

[1.0, 2.0, 3.0]

In [54]:
list(e) #slower

[1.0, 2.0, 3.0]

In [55]:
e[1]

2.0

In [58]:
e[1]=10 #array indexing 
e

array([  1.,  10.,   3.])

In [60]:
e.fill(0)
e

array([ 0.,  0.,  0.])

In [61]:
e[:]=1 #slower
e

array([ 1.,  1.,  1.])

In [67]:
a.dtype
e.dtype


dtype('float64')

In [70]:
c=np.array([1,2])
c

array([1, 2])

In [71]:
c.dtype

dtype('int32')

In [74]:
c[1]=5.8 #assigning a float into an int32 array will truncate decimal part.
c

array([1, 5])

In [75]:
c.fill(-5.8) #fill has the same behavior (assigning a float into an int32 array will truncate decimal part)
c

array([-5, -5])

In [76]:
k = np.arange(12.0).reshape(3,4)
k

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [77]:
k[0,3:7] #row=0 and 3to7 write

array([ 3.])

In [80]:
k[0,0:3] #row=0 and 0to3 write

array([ 0.,  1.,  2.])

In [81]:
k[:4,4:]

array([], shape=(3, 0), dtype=float64)