In [3]:
import numpy as np

celciusValue = [25.3,24.8,26.9,23.9,52.5,95.,12.0,55.9]

C = np.array(celciusValue)
C

array([ 25.3,  24.8,  26.9,  23.9,  52.5,  95. ,  12. ,  55.9])

In [5]:
F = (C*9/5)+32 #Fahrenheit transformation
F

array([  77.54,   76.64,   80.42,   75.02,  126.5 ,  203.  ,   53.6 ,
        132.62])

In [ ]:
# NumPy F = (C*9/5)+32 == Python F = [(x*9/5)+32 for x in celciusValue]

In [9]:
C = np.array(10*np.random.random(10)) #random 10 numbers *10
C

array([ 7.22888694,  4.35317753,  6.91496044,  7.09495542,  4.29776337,
        1.69001999,  0.96799506,  8.21214396,  2.89418808,  6.79597947])

In [10]:
F = (C*9/5)+32 #Fahrenheit transformation
F

array([ 45.01199648,  39.83571956,  44.44692878,  44.77091975,
        39.73597406,  35.04203598,  33.74239112,  46.78185914,
        37.20953855,  44.23276305])

In [20]:
x = 10*(np.random.random(5))
print(x)

[ 6.36984129  5.37812047  2.20712972  7.3970179   2.85902055]


In [21]:
y = 10*(np.random.random(5))
print(y)

[ 3.25361812  7.43561527  4.9683292   1.25497604  2.2657542 ]


In [22]:
distance = (np.sqrt(np.square(x)+np.square(y)))
print(distance)

[ 7.15268543  9.17673985  5.43651696  7.50272208  3.6479639 ]


In [23]:
total = np.sum(distance)
print(total)

32.9166282212
