In [3]:
import numpy as np

a=np.array([1,2,3])
b=np.array([3,4,5])
a+b

array([4, 6, 8])

In [8]:
x=np.arange(11.)
x

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [10]:
pi=3.14
a=(2*pi)/10. #multiple entire array by scalar value
a

0.628

In [11]:
a*x #inplace operations

array([ 0.   ,  0.628,  1.256,  1.884,  2.512,  3.14 ,  3.768,  4.396,
        5.024,  5.652,  6.28 ])

In [12]:
x *=a #inplace operations
x

array([ 0.   ,  0.628,  1.256,  1.884,  2.512,  3.14 ,  3.768,  4.396,
        5.024,  5.652,  6.28 ])

In [13]:
b=np.sin(x)
b

array([ 0.        ,  0.58752753,  0.95085946,  0.95135138,  0.58881556,
        0.00159265, -0.586238  , -0.95036513, -0.95184088, -0.5901021 ,
       -0.0031853 ])

In [14]:
d=np.array([1,2])
d*3.

array([ 3.,  6.])

In [15]:
e=np.array([5,6])

In [19]:
d+e

array([6, 8])

In [23]:
k=np.array([2.,3.,0.,1.])
k.min(axis=0) #find minimum value

0.0

In [24]:
k.argmin(axis=0) #find index of minimum value

2

In [26]:
k.max(axis=0)  #find maximum value

3.0

In [27]:
k.argmax(axis=0)  #find index of maximum value

1

In [36]:
m = np.array([(1,2,3),(4,5,6)],float)
m.mean(axis=0) # mean value fo each column (aritmetik oratalama)

array([ 2.5,  3.5,  4.5])

In [38]:
m.sum() # 1+2+3+4+5+6=21

21.0

In [39]:
sum(m)

array([ 5.,  7.,  9.])